import type { Metadata } from "next";
import { toolMetadata } from "@/lib/seo";
import ToolPageShell from "@/components/ToolPageShell";
import PdfToTextTool from "./PdfToTextTool";

export const metadata: Metadata = toolMetadata({
  category: "pdf",
  slug: "pdf-to-text",
  title: "PDF to Text — Extract Text from PDF as TXT or Markdown",
  description:
    "Pull the text out of a PDF and save it as plain text or Markdown. Copy it straight to your clipboard. Runs in your browser — no uploads, no sign-up.",
});

const FAQ_ITEMS = [
  {
    question: "My PDF came back empty. Why?",
    answer:
      "Almost certainly because it is a scan. A PDF made by Word or a browser contains real text objects that can be read directly. A PDF made by a scanner or a phone camera contains a photograph of a page — to a computer it is a picture, with no text in it anywhere. Turning that into text requires OCR, which this tool deliberately does not do.",
  },
  {
    question: "Why don't you support OCR?",
    answer:
      "OCR in a browser means tesseract.js: several megabytes of WebAssembly plus a trained language model per language, downloaded before the first character comes out. That is an order of magnitude more weight than anything else on this site, and it would still be noticeably worse than a desktop tool. Saying so is more useful than shipping something that half works.",
  },
  {
    question: "Why is the line spacing odd, or words run together?",
    answer:
      "PDF does not store paragraphs — it stores glyphs at coordinates. A justified line can arrive as a dozen separate fragments because the renderer adjusted the spacing between words. This tool reassembles lines using the end-of-line markers where a producer wrote them and falling back to vertical position where it did not, which handles most files well but cannot be perfect on complex multi-column layouts.",
  },
  {
    question: "Does it handle multi-column layouts and tables?",
    answer:
      "Partially. Text comes out in the order the PDF stores it, which for a two-column academic paper often means reading across both columns rather than down one. Tables lose their structure entirely and become runs of cell contents. For prose and single-column documents the output is usually clean; for anything with heavy layout, expect to tidy it up.",
  },
  {
    question: "What is the Markdown option for?",
    answer:
      "It adds a heading per page and a rule between pages, which makes long extractions navigable and gives a language model clear document structure to work with. If you are pasting a PDF into a chat assistant or a notes app, Markdown usually reads better than a wall of plain text.",
  },
  {
    question: "Is my PDF uploaded anywhere?",
    answer:
      "No. pdf.js reads the document inside your browser and the text never leaves the tab. That matters here more than on most tools — the text of a contract or a medical letter is exactly the kind of thing that should not be pasted into an unknown server.",
  },
];

export default function PdfToTextPage() {
  return (
    <ToolPageShell
      category="pdf"
      slug="pdf-to-text"
      title="PDF to Text"
      description="Extract the text from a PDF as plain text or Markdown, ready to paste anywhere."
      breadcrumbs={[
        { label: "Home", href: "/" },
        { label: "PDF", href: "/pdf" },
        { label: "PDF to Text" },
      ]}
      steps={[
        "Drop your PDF into the box above — it stays on your device.",
        "Choose plain text or Markdown.",
        "Extract, then copy the result or download it as a file.",
      ]}
      articleContent={
        <>
          <h2>Reading the text that is already there</h2>
          <p>
            A PDF that was generated by software — exported from Word, printed to
            PDF from a browser, produced by an invoicing system — contains real
            text. Each character is stored as a glyph reference with a position,
            and that text layer is what makes a PDF searchable and what lets you
            select a paragraph in a reader. This tool reads that layer directly.
          </p>
          <p>
            The whole operation is a read, not a conversion. Nothing is rendered,
            no pixels are involved, and the process is essentially instant even on
            a long document. What comes out is exactly the text the document
            author put in.
          </p>

          <h2>The one thing this cannot do</h2>
          <p>
            <strong>This is not OCR.</strong> That distinction is the difference
            between the tool working perfectly and returning nothing at all, so it
            is worth being clear about.
          </p>
          <p>
            When you scan a page, or photograph it with a phone, the resulting PDF
            contains an <em>image</em>. There is no text in the file — a human
            reading it on screen is doing character recognition with their eyes,
            and the computer has no equivalent unless something has run optical
            character recognition and written a text layer back in. If your PDF
            comes back empty here, that is what happened, and the tool says so
            rather than handing you a blank file and letting you wonder.
          </p>
          <p>
            Some scanners and document management systems do run OCR
            automatically, in which case the scan has a text layer and this tool
            reads it fine. Whether yours did is easy to check: open the PDF in any
            reader and try to select a word. If the cursor draws a selection box
            over the whole page instead of highlighting text, there is nothing to
            extract.
          </p>

          <h2>How lines get put back together</h2>
          <p>
            PDF stores glyphs at coordinates rather than paragraphs, so
            reconstructing readable lines takes some work. A justified line often
            arrives as many separate fragments because the renderer nudged the
            spacing between individual words to make the margins align.
          </p>
          <p>
            The extractor uses the end-of-line markers where the PDF producer
            wrote them, and falls back to comparing vertical positions where it
            did not — a fragment that jumped down the page started a new line.
            This handles ordinary prose well. Multi-column layouts and tables are
            harder, because the reading order stored in the file does not always
            match the reading order a human would use.
          </p>

          <h2>Plain text or Markdown</h2>
          <p>
            <strong>Plain text</strong> gives you the words with a blank line
            between pages. It is the right choice when the text is going into
            another program that will do its own formatting.
          </p>
          <p>
            <strong>Markdown</strong> adds a heading for each page and a horizontal
            rule between them. This is more useful than it sounds when the
            destination is a notes app, a wiki, or a language model — the page
            boundaries survive, so you can still tell where something came from in
            a fifty-page extraction.
          </p>

          <h2>Common uses</h2>
          <ul>
            <li>Quoting from a report without retyping it</li>
            <li>Getting a contract into a text editor for comparison</li>
            <li>Feeding a document to an AI assistant that cannot read PDFs</li>
            <li>Searching a document your reader will not search properly</li>
            <li>Recovering text from a PDF whose source file is long gone</li>
          </ul>
        </>
      }
      faqItems={FAQ_ITEMS}
    >
      <PdfToTextTool />
    </ToolPageShell>
  );
}
