import type { Metadata } from "next";
import { toolMetadata } from "@/lib/seo";
import ToolPageShell from "@/components/ToolPageShell";
import PdfToCsvTool from "./PdfToCsvTool";

export const metadata: Metadata = toolMetadata({
  category: "pdf",
  slug: "pdf-to-csv",
  title: "PDF to CSV — Extract Tables from PDF to Spreadsheet",
  description:
    "Pull tables out of a PDF into a CSV you can open in Excel, Sheets or anything else. Columns are rebuilt from the page layout. No uploads, no sign-up.",
});

const FAQ_ITEMS = [
  {
    question: "Does this work on a scanned PDF?",
    answer:
      "No. This reads the text layer — the actual characters stored in the file. A scan is a picture of a page with no text layer at all, so there is nothing to extract. Recovering it would need OCR, which this site does not do.",
  },
  {
    question: "The columns came out wrong. Why?",
    answer:
      "Usually because the table is centred, uses merged cells, or has cells that wrap onto several lines. Column detection works from the left edges of text, so anything that weakens that alignment weakens the result. A cleanly left-aligned table converts very reliably.",
  },
  {
    question: "What is the difference between this and PDF to Excel?",
    answer:
      "The output format only — both use the same extraction. Choose CSV when you want something universal and text-based, or when you are feeding another program. Choose Excel when you want a real workbook, or one sheet per page.",
  },
  {
    question: "Why is everything in one file when my PDF had many pages?",
    answer:
      "CSV has no concept of sheets, so per-page splitting would mean a ZIP of files. Pages are appended one after another with a blank row between them, which is what most people want to paste into a spreadsheet anyway.",
  },
  {
    question: "Is my PDF uploaded?",
    answer:
      "No. The text layer is read by pdf.js in your browser and the CSV is built there. Nothing is sent to a server.",
  },
];

export default function Page() {
  return (
    <ToolPageShell
      category="pdf"
      slug="pdf-to-csv"
      title="PDF to CSV"
      description="Extract the tables from a PDF into a plain CSV file."
      breadcrumbs={[
        { label: "Home", href: "/" },
        { label: "PDF", href: "/pdf" },
        { label: "PDF to CSV" },
      ]}
      steps={[
        "Drop in a PDF that contains a table",
        "Extract",
        "Download the CSV",
      ]}
      articleContent={
        <>
          <h2>How columns are recovered</h2>
          <p>
            A PDF does not contain a table. It contains a list of text fragments, each
            with a position on the page, and the appearance of a table is produced by
            where those fragments happen to sit. Nothing in the file says “this is a
            column”.
          </p>
          <p>
            So the columns have to be inferred. This tool groups fragments into rows by
            their vertical position, then looks at where runs of text start horizontally
            across all those rows. Left edges that recur down the page are column
            boundaries — that repetition is what a column actually is, visually.
          </p>
          <h2>What works and what does not</h2>
          <p>
            Clean, regularly aligned tables come out almost perfectly. Financial
            statements, exported reports and anything generated by software rather than
            laid out by hand are the best cases.
          </p>
          <p>
            Merged cells, multi-line cells and columns that are centred rather than
            left-aligned are where the heuristic struggles, because the visual cue it
            depends on is weaker. Prose is the worst case: a paragraph has one column,
            and the result is one long thin CSV.
          </p>
          <h2>Why the file starts with a byte order mark</h2>
          <p>
            The CSV is written as UTF-8 with a BOM. Without it, Excel on Windows assumes
            the system codepage and every accented character in the extraction turns to
            mojibake the moment the file is opened — the single most common complaint
            about CSV exports anywhere.
          </p>
          <p>
            The BOM is invisible in every modern tool and costs three bytes. If you need
            it gone for a strict downstream parser, any text editor will remove it.
          </p>
        </>
      }
      faqItems={FAQ_ITEMS}
    >
      <PdfToCsvTool />
    </ToolPageShell>
  );
}
